# Generated by Django 5.2.3 on 2025-07-18 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('formula', models.CharField(blank=True, default='', help_text='e.g. C8H9NO2 for Paracetamol', max_length=100, verbose_name='Chemical Formula')),
                ('batch_no', models.CharField(blank=True, default='', verbose_name='Bactch No')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('retailers_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Purchase Price (Rs)')),
                ('packet_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Selling Price per Packet (Rs)')),
                ('box_count', models.PositiveIntegerField(default=1, editable=False, verbose_name='Number of Boxes')),
                ('units_per_box', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Units per Packet')),
                ('rack_number', models.CharField(max_length=20)),
                ('expiry_date', models.DateField()),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage (%)'), ('flat', 'Flat Amount (Rs)')], default='percent', max_length=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.PositiveIntegerField(default=0)),
                ('static_stock', models.PositiveIntegerField(default=0, verbose_name='Initial Stock (Static)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_purchased', models.PositiveIntegerField(default=0, verbose_name='Total Units Purchased (All Time)')),
                ('total_purchase_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Purchase Amount (All Time)')),
            ],
        ),
    ]
