# Generated by Django 5.2.3 on 2025-07-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='purchase_history',
            field=models.JSONField(default=list, help_text='Stores all stock changes with timestamps', verbose_name='Complete Purchase History'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='batch_no',
            field=models.CharField(blank=True, default='', verbose_name='Batch No'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='static_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Current Reference Stock'),
        ),
    ]
