# Generated by Django 5.2.3 on 2025-07-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_medicine_purchase_history_alter_medicine_batch_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='purchase_history',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='batch_no',
            field=models.CharField(blank=True, default='', verbose_name='Bactch No'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='static_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Initial Stock (Static)'),
        ),
    ]
