# Generated by Django 5.2.3 on 2025-07-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_remove_medicine_purchase_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='last_purchase_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='medicine',
            name='last_purchase_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='last_purchase_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicine',
            name='new_stock',
            field=models.PositiveIntegerField(default=0, help_text='Updated stock value during edits', verbose_name='New Stock'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='purchase_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
