# Generated by Django 5.2.3 on 2025-07-22 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_medicine_last_purchase_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='box_count',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='last_purchase_amount',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='last_purchase_date',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='last_purchase_quantity',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='new_stock',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='purchase_notes',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='static_stock',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='total_purchase_amount',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='total_purchased',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='batch_no',
            field=models.CharField(blank=True, default='', verbose_name='Batch No'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='formula',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Chemical Formula'),
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='medicine.medicine')),
            ],
            options={
                'verbose_name_plural': 'Purchase Histories',
                'ordering': ['-purchase_date'],
            },
        ),
    ]
