# Generated by Django 5.2.3 on 2025-07-22 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0005_remove_medicine_box_count_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurchaseHistory',
            new_name='PurchaseRecord',
        ),
        migrations.AlterModelOptions(
            name='purchaserecord',
            options={'ordering': ['-purchase_date'], 'verbose_name_plural': 'Purchase Records'},
        ),
        migrations.AlterField(
            model_name='medicine',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Current Stock'),
        ),
    ]
