# Generated by Django 5.2.3 on 2025-07-25 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_options_sale_fully_returned_items_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-sale_date']},
        ),
        migrations.RemoveField(
            model_name='sale',
            name='fully_returned_items_count',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='net_amount',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='returned_amount',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='returned_items_count',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='total_profit',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='returned_price',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='returned_quantity',
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
