# Generated by Django 5.2.3 on 2025-07-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_return_options_remove_return_processed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='restocked',
            field=models.BooleanField(default=False),
        ),
    ]
