# Generated by Django 5.2.3 on 2025-07-25 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_return_restocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='restocked',
        ),
    ]
