# Generated by Django 5.2.3 on 2025-07-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0006_rename_purchasehistory_purchaserecord_and_more'),
        ('sales', '0008_remove_return_restocked'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['-returned_at'], name='sales_retur_returne_cef48e_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['sale'], name='sales_retur_sale_id_d5b460_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['medicine'], name='sales_salei_medicin_478583_idx'),
        ),
    ]
