# Generated by Django 5.2.3 on 2025-07-26 03:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_return_sales_retur_returne_cef48e_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='return',
            name='sales_retur_returne_cef48e_idx',
        ),
        migrations.RemoveIndex(
            model_name='return',
            name='sales_retur_sale_id_d5b460_idx',
        ),
        migrations.RemoveIndex(
            model_name='saleitem',
            name='sales_salei_medicin_478583_idx',
        ),
        migrations.AddField(
            model_name='sale',
            name='profit_before_returns',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
