# Generated by Django 5.2.3 on 2025-07-26 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_remove_return_sales_retur_returne_cef48e_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='return',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-sale_date']},
        ),
        migrations.RemoveIndex(
            model_name='returnitem',
            name='sales_retur_sale_it_ecc8fa_idx',
        ),
        migrations.RemoveIndex(
            model_name='sale',
            name='sales_sale_sale_da_2fd927_idx',
        ),
        migrations.RemoveIndex(
            model_name='saleitem',
            name='sales_salei_sale_id_413ea3_idx',
        ),
        migrations.RemoveField(
            model_name='return',
            name='is_processed',
        ),
        migrations.RemoveField(
            model_name='returnitem',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='fully_returned_items_count',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='net_amount',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='profit_before_returns',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='returned_amount',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='returned_items_count',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='total_profit',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='returned_price',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='returned_quantity',
        ),
        migrations.AlterField(
            model_name='return',
            name='refund_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='returned_price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='purchase_price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='selling_price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
