# Generated by Django 5.2.3 on 2025-07-26 04:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_alter_return_options_alter_sale_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='net_amount_cached',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='returned_amount_cached',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_profit_cached',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='returned_quantity_cached',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
