# Generated by Django 5.2.3 on 2025-07-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_sale_net_amount_cached_sale_returned_amount_cached_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='returned_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
