# Generated by Django 5.2.3 on 2025-07-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_alter_return_refund_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySalesSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_returns', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sale_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Daily Sales Summaries',
            },
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={},
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sale_date'], name='sales_sale_sale_da_2fd927_idx'),
        ),
        migrations.AddIndex(
            model_name='dailysalessummary',
            index=models.Index(fields=['date'], name='sales_daily_date_84fae3_idx'),
        ),
    ]
