# Generated by Django 5.2.3 on 2025-07-26 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_dailysalessummary_alter_sale_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailysalessummary',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='dailysalessummary',
            name='sales_daily_date_84fae3_idx',
        ),
    ]
