# Generated by Django 5.2.3 on 2025-07-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_alter_dailysalessummary_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailysalessummary',
            options={'verbose_name_plural': 'Daily Sales Summaries'},
        ),
        migrations.RemoveField(
            model_name='dailysalessummary',
            name='sale_count',
        ),
        migrations.AddField(
            model_name='dailysalessummary',
            name='net_sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailysalessummary',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailysalessummary',
            name='total_returns',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailysalessummary',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
