# Generated by Django 5.2.3 on 2025-07-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_alter_dailysalessummary_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailySalesSummary',
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-sale_date']},
        ),
        migrations.RemoveIndex(
            model_name='sale',
            name='sales_sale_sale_da_2fd927_idx',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='net_amount_cached',
            new_name='_net_amount',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='returned_amount_cached',
            new_name='_returned_amount',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='total_profit_cached',
            new_name='_total_profit',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='returned_quantity_cached',
        ),
        migrations.AlterField(
            model_name='return',
            name='refund_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='returned_price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
