# Generated by Django 5.2.3 on 2025-07-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0006_rename_purchasehistory_purchaserecord_and_more'),
        ('sales', '0018_alter_sale_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='returned_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='return',
            name='returned_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['sale'], name='sales_retur_sale_id_d5b460_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['-returned_at'], name='sales_retur_returne_cef48e_idx'),
        ),
        migrations.AddIndex(
            model_name='returnitem',
            index=models.Index(fields=['return_entry'], name='sales_retur_return__1ad5d7_idx'),
        ),
        migrations.AddIndex(
            model_name='returnitem',
            index=models.Index(fields=['sale_item'], name='sales_retur_sale_it_ecc8fa_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['_total_profit'], name='sales_sale__total__2f4586_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['_net_amount'], name='sales_sale__net_am_ff7c40_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['sale'], name='sales_salei_sale_id_413ea3_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['medicine'], name='sales_salei_medicin_478583_idx'),
        ),
    ]
