# Generated by Django 5.2.3 on 2025-07-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_saleitem_returned_quantity_alter_return_returned_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='return',
            name='sales_retur_sale_id_d5b460_idx',
        ),
        migrations.RemoveIndex(
            model_name='return',
            name='sales_retur_returne_cef48e_idx',
        ),
        migrations.RemoveIndex(
            model_name='returnitem',
            name='sales_retur_return__1ad5d7_idx',
        ),
        migrations.RemoveIndex(
            model_name='returnitem',
            name='sales_retur_sale_it_ecc8fa_idx',
        ),
        migrations.RemoveIndex(
            model_name='sale',
            name='sales_sale__total__2f4586_idx',
        ),
        migrations.RemoveIndex(
            model_name='sale',
            name='sales_sale__net_am_ff7c40_idx',
        ),
        migrations.RemoveIndex(
            model_name='saleitem',
            name='sales_salei_sale_id_413ea3_idx',
        ),
        migrations.RemoveIndex(
            model_name='saleitem',
            name='sales_salei_medicin_478583_idx',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='returned_quantity',
        ),
        migrations.AlterField(
            model_name='return',
            name='returned_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
