# Generated by Django 5.2.3 on 2025-07-29 11:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_remove_return_sales_retur_sale_id_d5b460_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnitem',
            name='discount_restored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='allocated_sale_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
