# Generated by Django 5.2.3 on 2025-07-29 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_returnitem_discount_restored_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnitem',
            name='discount_restored',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='allocated_sale_discount',
        ),
    ]
